export const entidades = [
	{behavior: "Controlavel", image: "../images/Steve.webp", name: "Steve", type: "Jogador", description: "O personagem mais icônico do jogo a qual fez com que todos podessem começar a sua aventura o controlando" },
  	{behavior: "Passivo",image: "../images/Porco.webp", name: "Porco", type: "Animal", description: "O monstro que tem a melhor falha de qualquer jogo na história com a falha de textura trazendo o icônico monstro que hoje em dia é o rosto do jogo" },
  	{behavior: "Passivo",image: "../images/Vaca.webp", name: "Vaca", type: "Animal", description: "Não me pergunte oque tem naquele bendito leite por que o coisa que cura tudo quanto efeito negativo, esse bixo é estremamente valioso numa gameplay de hardcore" },
  	{behavior: "Passivo",image: "../images/Ovelha.webp", name: "Ovelha", type: "Animal", description: "O monstro que veio ao mundo com a tag de primeiro mob com algo mais raro do jogo, com uma cor extremamente especial quando vista selvagem" },
  	{behavior: "Passivo",image: "../images/Villager.webp", name: "Villager", type: "NPC", description: "O monstro mais util do jogo pós suas trocas vem o livro de encantamento mais roubado do jogo, fazendo eles ser extremamentes valiosos para todos os tipos de jogadores" },
  	{behavior: "Agressivo",image: "../images/Creeper.webp", name: "Creeper", type: "Monstro", description: "O mob com o som que mais trás tristeza no coração dos jogadores quando eles estão numa sala de baús organizada, suas explozões custou varias horas de jogo perdidas" },
  	{behavior: "Agressivo",image: "../images/Zombie.webp", name: "Zombie", type: "Monstro", description: "O mob com a mecanica que os jogadores mais abusa em farms ou trocas mais baratas mais usando seu fator medo para que venha assustar os Villagers, ou se não converte-los em zumbi" },
  	{behavior: "Agressivo",image: "../images/Esqueleto.webp", name: "Esqueleto", type: "Monstro", description: "O mob com a mira mais mentirosa de todo o jogo, não me pergunte por que ele tem esses angulus com o arco pós nem o criador do jogo sabe explicar" },
  	{behavior: "Neutro/Agressivo",image: "../images/Aranha.webp", name: "Aranha", type: "Monstro", description: "Um dos comportamentos mais interessantes vem deste monstro pós a partir de um nivel 11 de iluminação no ambiente ela fica agressiva para cima do jogador" },
	{behavior: "Neutro/Agressivo",image: "../images/Enderman.webp", name: "Enderman", type: "Monstro", description: "O mob que mais carrega misterio sobre suas origens no mundo de minecraft, não sabemos o motivo de ele ser agressivo ao olhar nos seus olhos mas as vezes por olhar neles vem uma morte iminente" },
	{rarity: "baixa", image: "../images/espada_de_madeira.png", name: "Espada de madeira", type: "Item", description: "A Primeira espada do jogo para com que o jogador venha a se defender mesmo sendo a mais fraca e menos duravel ela ainda serve para alguma coisa"},
	{rarity: "baixa", image: "../images/espada_de_pedra.png",  name: "Espada de pedra", type: "Item", description: "A espada que é a direta evolução da espada de madeira fazendo com que ela ser um upgrade muito alto de dano e durabilidade"}
]